[2019-06-01 00:00:00.002] [INFO] console - 现在时间： 2019-05-31T16:00:00.002Z
[2019-06-01 09:44:12.689] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 09:44:12.690] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 09:59:02.572] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 09:59:02.573] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 10:35:11.762] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 10:35:11.763] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 10:35:23.371] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 10:35:23.372] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 10:36:03.865] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 10:36:03.866] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 10:36:09.943] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 10:36:09.944] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 10:36:12.669] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 10:36:12.670] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 10:36:14.541] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 10:36:14.542] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 10:36:27.075] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 10:36:27.076] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 10:37:31.172] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:37:33.958] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:37:36.115] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:37:38.479] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:39:10.243] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 10:39:10.244] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 10:41:26.053] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:41:27.563] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:41:28.970] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:41:30.708] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:41:33.938] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:41:37.257] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:41:38.330] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:41:39.539] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:41:41.989] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:41:44.031] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 10:41:44.745] [WARN] console - detail：公告详情id不能为空！
[2019-06-01 11:13:29.307] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:13:29.308] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:13:31.978] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:13:31.979] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:14:00.511] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:14:00.512] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:14:01.859] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:14:01.860] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:14:19.669] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:14:19.670] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:15:35.904] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:15:35.904] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:15:36.398] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:15:36.399] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:17:43.981] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:17:43.981] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:17:47.338] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:17:47.340] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:21:25.617] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:21:25.618] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:21:53.946] [ERROR] console - Api-URL:http://172.31.15.184:8081/rule/getRuleContent--->{"code":"ssq"}---------------error
[2019-06-01 11:21:53.954] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:21:53.955] [ERROR] console - Cannot read property 'introduceContent' of undefined
[2019-06-01 11:21:53.976] [ERROR] console - TypeError: Cannot read property 'introduceContent' of undefined
    at SsqController._callee$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/controllers/digit/ssq.controller.js:108:50)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:21:54.029] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"fc3d"}---------------error
[2019-06-01 11:21:54.030] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:21:54.031] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:21:54.044] [ERROR] console - TypeError: Cannot read property 'introduceContent' of undefined
    at Fc3dController._callee$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/controllers/digit/fc3d.controller.js:114:50)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:21:55.486] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"lotteryCodes":["qlc"],"categoryIds":[37,39,40,41],"pageSize":6}---------------error
[2019-06-01 11:21:55.487] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:22:05.489] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"qlc"}---------------error
[2019-06-01 11:22:05.490] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:22:05.491] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:22:05.497] [ERROR] console - TypeError: Cannot read property 'introduceContent' of undefined
    at QlcController._callee$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/controllers/digit/qlc.controller.js:107:50)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:22:12.985] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"fc3d"}---------------error
[2019-06-01 11:22:12.987] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:22:12.988] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:22:14.568] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"fc3d"}---------------error
[2019-06-01 11:22:14.569] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:22:14.570] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:22:16.228] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"fc3d"}---------------error
[2019-06-01 11:22:16.230] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:22:16.231] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:22:16.482] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"fc3d"}---------------error
[2019-06-01 11:22:16.483] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:22:16.484] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:22:16.485] [ERROR] console - TypeError: Cannot read property 'introduceContent' of undefined
    at Fc3dController._callee$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/controllers/digit/fc3d.controller.js:114:50)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:22:40.729] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"lotteryCodes":["qlc"],"categoryIds":[37,39,40,41],"pageSize":6}---------------error
[2019-06-01 11:22:40.730] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:22:45.724] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"ssq"}---------------error
[2019-06-01 11:22:45.725] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:22:45.726] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:22:45.729] [ERROR] console - TypeError: Cannot read property 'introduceContent' of undefined
    at SsqController._callee$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/controllers/digit/ssq.controller.js:108:50)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:22:50.713] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"fc3d"}---------------error
[2019-06-01 11:22:50.714] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:22:50.715] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:22:50.717] [ERROR] console - TypeError: Cannot read property 'introduceContent' of undefined
    at Fc3dController._callee$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/controllers/digit/fc3d.controller.js:114:50)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:22:50.743] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"qlc"}---------------error
[2019-06-01 11:22:50.743] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:22:50.744] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:23:26.380] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":32,"pageIndex":1,"pageSize":7}---------------error
[2019-06-01 11:23:26.382] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:23:26.397] [ERROR] console - TypeError: Cannot read property 'data' of undefined
    at _11x5Service._callee6$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/services/public/lottery.service.js:1341:82)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:23:26.442] [ERROR] console - 时间组件参数：awardTime.awardTimeInterval为空！
[2019-06-01 11:23:30.619] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":32,"pageIndex":1,"pageSize":7}---------------error
[2019-06-01 11:23:30.620] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:23:30.620] [ERROR] console - TypeError: Cannot read property 'data' of undefined
    at _11x5Service._callee6$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/services/public/lottery.service.js:1341:82)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:23:30.662] [ERROR] console - 时间组件参数：awardTime.awardTimeInterval为空！
[2019-06-01 11:23:44.434] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":34,"pageIndex":1,"pageSize":7}---------------error
[2019-06-01 11:23:44.435] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:23:44.437] [ERROR] console - TypeError: Cannot read property 'data' of undefined
    at K3Service._callee6$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/services/public/lottery.service.js:1341:82)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:23:44.438] [ERROR] console - getResultSumValue：参数出现问题！
[2019-06-01 11:23:44.474] [ERROR] console - 时间组件参数：awardTime.awardTimeInterval为空！
[2019-06-01 11:24:23.595] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":33,"pageIndex":1,"pageSize":7}---------------error
[2019-06-01 11:24:23.596] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:24:23.597] [ERROR] console - TypeError: Cannot read property 'data' of undefined
    at KL10Service._callee6$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/services/public/lottery.service.js:1341:82)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:24:23.638] [ERROR] console - 时间组件参数：awardTime.awardTimeInterval为空！
[2019-06-01 11:25:06.724] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":35,"pageIndex":1,"pageSize":7}---------------error
[2019-06-01 11:25:06.725] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:25:06.726] [ERROR] console - TypeError: Cannot read property 'data' of undefined
    at SSCService._callee6$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/services/public/lottery.service.js:1341:82)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:25:06.770] [ERROR] console - 时间组件参数：awardTime.awardTimeInterval为空！
[2019-06-01 11:25:31.405] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"pl3"}---------------error
[2019-06-01 11:25:31.406] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:25:31.407] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:25:31.411] [ERROR] console - TypeError: Cannot read property 'introduceContent' of undefined
    at Pl3Controller._callee$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/controllers/digit/pl3.controller.js:108:50)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:25:48.117] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"qxc"}---------------error
[2019-06-01 11:25:48.119] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:25:48.119] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:25:50.354] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"qxc"}---------------error
[2019-06-01 11:25:50.356] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:25:50.357] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:25:50.362] [ERROR] console - TypeError: Cannot read property 'introduceContent' of undefined
    at QxcController._callee$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/controllers/digit/qxc.controller.js:108:50)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:26:29.713] [ERROR] console - Api-URL:http://172.31.15.184:8081/contactus/GetContactuContent--->{"id":25}---------------error
[2019-06-01 11:26:29.715] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:26:30.397] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_article_banner"}---------------error
[2019-06-01 11:26:30.398] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:26:40.487] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetTotalArticleList--->{"categoryIds":[32,33,34,35],"pageSize":8}---------------error
[2019-06-01 11:26:40.488] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:26:50.490] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[5,6],"pageSize":8}---------------error
[2019-06-01 11:26:50.491] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:26:53.522] [ERROR] console - Api-URL:http://172.31.15.184:8081/contactus/GetContactuContent--->{"id":28}---------------error
[2019-06-01 11:26:53.523] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:26:58.423] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:26:58.424] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:26:59.633] [ERROR] console - Api-URL:http://172.31.15.184:8081/contactus/GetContactuContent--->{"id":28}---------------error
[2019-06-01 11:26:59.634] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:00.494] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"lotteryCodes":["dlt","fc3d","pl3","pl5","qlc","qxc","ssq"],"categoryIds":[37,39,40,41],"pageSize":8}---------------error
[2019-06-01 11:27:00.495] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:00.496] [ERROR] console - articleClassification: 参数_articleArrayList不能为空或者类型需要是数组类型！
[2019-06-01 11:27:06.515] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:27:06.517] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:27:08.430] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:27:08.432] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:10.500] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":9}---------------error
[2019-06-01 11:27:10.501] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:10.511] [ERROR] console - TypeError: Cannot read property 'data' of null
    at DealWithCommonService._callee10$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/services/public/dealWithCommon.service.js:1320:38)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:27:16.523] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:27:16.525] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:18.694] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:27:18.695] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:20.519] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"article"}---------------error
[2019-06-01 11:27:20.520] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:26.536] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:27:26.537] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:30.525] [ERROR] console - Api-URL:http://172.31.15.184:8081/plan/GetPlanArticleList--->{"categoryIds":[1],"pageSize":15}---------------error
[2019-06-01 11:27:30.527] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:30.709] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:27:30.710] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:30.731] [ERROR] console - Debug:internal, implementation, error
    TemplateError: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null
[2019-06-01 11:27:32.780] [ERROR] console - Api-URL:http://172.31.15.184:8081/contactus/GetContactuContent--->{"id":23}---------------error
[2019-06-01 11:27:32.781] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:36.381] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:27:36.382] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:27:38.296] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:27:38.297] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:38.306] [ERROR] console - Debug:internal, implementation, error
    TemplateError: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null
[2019-06-01 11:27:38.800] [ERROR] console - Api-URL:http://172.31.15.184:8081/contactus/GetContactuContent--->{"id":23}---------------error
[2019-06-01 11:27:38.801] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:39.901] [ERROR] console - Api-URL:http://172.31.15.184:8081/contactus/GetContactuContent--->{"id":23}---------------error
[2019-06-01 11:27:39.902] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:40.136] [ERROR] console - Api-URL:http://172.31.15.184:8081/contactus/GetContactuContent--->{"id":23}---------------error
[2019-06-01 11:27:40.137] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:40.233] [ERROR] console - Api-URL:http://172.31.15.184:8081/contactus/GetContactuContent--->{"id":23}---------------error
[2019-06-01 11:27:40.234] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:40.366] [ERROR] console - Api-URL:http://172.31.15.184:8081/contactus/GetContactuContent--->{"id":23}---------------error
[2019-06-01 11:27:40.367] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:41.014] [ERROR] console - Api-URL:http://172.31.15.184:8081/contactus/GetContactuContent--->{"id":23}---------------error
[2019-06-01 11:27:41.015] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:46.138] [ERROR] console - Api-URL:http://172.31.15.184:8081/contactus/GetContactuContent--->{"id":28}---------------error
[2019-06-01 11:27:46.139] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:46.389] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:27:46.390] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:27:56.653] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:27:56.655] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:28:08.421] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:28:08.421] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:28:08.429] [ERROR] console - Debug:internal, implementation, error
    TemplateError: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null
[2019-06-01 11:28:12.752] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:28:12.752] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:28:22.761] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:28:22.763] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:28:29.560] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:28:29.560] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:28:33.023] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:28:33.024] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:28:39.568] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:28:39.569] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:28:44.786] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:28:44.788] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:28:44.797] [ERROR] console - Debug:internal, implementation, error
    TemplateError: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null
[2019-06-01 11:28:49.834] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:28:49.835] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:29:01.031] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:29:01.032] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:29:01.595] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:29:01.596] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:29:01.610] [ERROR] console - Debug:internal, implementation, error
    TemplateError: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null
[2019-06-01 11:29:11.170] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:29:11.171] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:29:21.431] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:29:21.433] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:29:33.202] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:29:33.203] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:29:33.218] [ERROR] console - Debug:internal, implementation, error
    TemplateError: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null
[2019-06-01 11:33:20.539] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:33:20.540] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:33:30.619] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:33:30.621] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:33:40.892] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:33:40.893] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:33:52.665] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:33:52.666] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:33:52.751] [ERROR] console - Debug:internal, implementation, error
    TemplateError: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null
[2019-06-01 11:34:23.799] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:34:23.800] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:34:27.377] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"lotteryCodes":["ssq"],"categoryIds":[37,39,40,41],"pageSize":6}---------------error
[2019-06-01 11:34:27.379] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:34:28.662] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:34:28.664] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:34:33.888] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:34:33.890] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:34:37.383] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"ssq"}---------------error
[2019-06-01 11:34:37.385] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:34:37.386] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:34:37.387] [ERROR] console - TypeError: Cannot read property 'introduceContent' of undefined
    at SsqController._callee$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/controllers/digit/ssq.controller.js:108:50)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:34:38.671] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:34:38.673] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:34:44.152] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:34:44.153] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:34:48.685] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:34:48.687] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:34:55.165] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:34:55.166] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:34:55.178] [ERROR] console - Debug:internal, implementation, error
    TemplateError: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null
[2019-06-01 11:34:58.596] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:34:58.597] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:34:59.702] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:34:59.703] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:35:08.604] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:35:08.604] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:35:18.868] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:35:18.869] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:35:26.204] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:35:26.205] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:35:29.879] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:35:29.880] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:35:36.350] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:35:36.351] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:35:46.618] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:35:46.619] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:35:57.634] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:35:57.635] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:35:57.648] [ERROR] console - Debug:internal, implementation, error
    TemplateError: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null
[2019-06-01 11:36:08.697] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:36:08.698] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:36:16.567] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:36:16.568] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:36:17.629] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":32,"pageIndex":1,"pageSize":7}---------------error
[2019-06-01 11:36:17.630] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:17.631] [ERROR] console - TypeError: Cannot read property 'data' of undefined
    at _11x5Service._callee6$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/services/public/lottery.service.js:1341:82)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:36:18.123] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":34,"pageIndex":1,"pageSize":7}---------------error
[2019-06-01 11:36:18.124] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:18.125] [ERROR] console - TypeError: Cannot read property 'data' of undefined
    at K3Service._callee6$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/services/public/lottery.service.js:1341:82)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:36:18.126] [ERROR] console - getResultSumValue：参数出现问题！
[2019-06-01 11:36:18.177] [ERROR] console - 时间组件参数：awardTime.awardTimeInterval为空！
[2019-06-01 11:36:18.250] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"lotteryCodes":["ssq"],"categoryIds":[37,39,40,41],"pageSize":6}---------------error
[2019-06-01 11:36:18.251] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:18.697] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":33,"pageIndex":1,"pageSize":7}---------------error
[2019-06-01 11:36:18.698] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:18.699] [ERROR] console - TypeError: Cannot read property 'data' of undefined
    at KL10Service._callee6$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/services/public/lottery.service.js:1341:82)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:36:18.736] [ERROR] console - 时间组件参数：awardTime.awardTimeInterval为空！
[2019-06-01 11:36:18.803] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:36:18.804] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:26.578] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:36:26.580] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:28.255] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":37,"pageIndex":1,"pageSize":16,"lotterycode":"ssq"}---------------error
[2019-06-01 11:36:28.257] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:28.258] [ERROR] console - Cannot read property 'data' of undefined
[2019-06-01 11:36:28.260] [ERROR] console - TypeError: Cannot read property 'introduceContent' of undefined
    at SsqController._callee$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/controllers/digit/ssq.controller.js:108:50)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:36:29.075] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:36:29.076] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:31.140] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:36:31.141] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:36:34.990] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/getArticles--->{"categoryId":33,"pageIndex":1,"pageSize":7}---------------error
[2019-06-01 11:36:34.992] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:34.993] [ERROR] console - TypeError: Cannot read property 'data' of undefined
    at KL10Service._callee6$ (E:/dev-001/xq_eycp/Eycp.SitePC/server/src/services/public/lottery.service.js:1341:82)
    at tryCatch (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2019-06-01 11:36:35.038] [ERROR] console - 时间组件参数：awardTime.awardTimeInterval为空！
[2019-06-01 11:36:36.590] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:36:36.592] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:40.150] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:36:40.150] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:41.272] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:36:41.273] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:47.603] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:36:47.604] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:36:51.541] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:36:51.542] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:37:02.554] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:37:02.555] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:37:02.564] [ERROR] console - Debug:internal, implementation, error
    TemplateError: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null
[2019-06-01 11:37:03.641] [ERROR] console - Api-URL:http://localhost:35129/home/GetAdData--->{"codes":"eycp_home_banner"}---------------error
[2019-06-01 11:37:03.642] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:35129
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[2019-06-01 11:37:13.649] [ERROR] console - Api-URL:http://172.31.15.184:8081/notice/getNotices--->{"pageIndex":1,"pageSize":5}---------------error
[2019-06-01 11:37:13.650] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:37:23.910] [ERROR] console - Api-URL:http://172.31.15.184:8081/article/GetArticleList--->{"categoryIds":[6,32,33,34,35,36],"pageSize":5}---------------error
[2019-06-01 11:37:23.911] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:37:34.927] [ERROR] console - Api-URL:http://172.31.15.184:8081//friendlink/getlist--->{"code":"home"}---------------error
[2019-06-01 11:37:34.928] [ERROR] console - Error: timeout of 10000ms exceeded
    at createError (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (E:\dev-001\xq_eycp\Eycp.SitePC\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2019-06-01 11:37:34.943] [ERROR] console - Debug:internal, implementation, error
    TemplateError: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null: E:\dev-001\xq_eycp\Eycp.SitePC\server\src\views\home\index.html:73:29
    71|                     <div class="al_listBlock">
    72|                         <ul>
 >> 73|                             {{if noticeList.data}}
    74|                                 {{if noticeList.data.length > 0}}
    75|                                     {{each noticeList.data  list }}
    76|                                         <li><a href="/notice/detail-{{@list.id }}.html"  class="title" target="_blank">{{@list.title }}</a></li>

RuntimeError: Cannot read property 'data' of null
